export const dummySkills: SkillRecord[] = [
  {
    id: "1",
    title: "Web Search",
    slug: "web-search",
    description: "Enables agents to query the web and retrieve up-to-date information from search engines.",
    category: "Research",
    tags: ["search", "web", "retrieval"],
    installCommand: "npx skild add web-search",
    createdAt: "2026-04-01T10:00:00Z",
    authorClerkId: "user_abc123",
    authorEmail: "alice@example.com",
  },
  {
    id: "2",
    title: "Code Executor",
    slug: "code-executor",
    description: "Allows agents to run sandboxed code snippets in Python, JavaScript, or TypeScript and return results.",
    category: "Development",
    tags: ["code", "execution", "sandbox"],
    installCommand: "npx skild add code-executor",
    createdAt: "2026-04-05T14:30:00Z",
    authorClerkId: "user_def456",
    authorEmail: "bob@example.com",
  },
  {
    id: "3",
    title: "PDF Reader",
    slug: "pdf-reader",
    description: "Extracts and parses text content from PDF documents for downstream agent processing.",
    category: "Document",
    tags: ["pdf", "parsing", "document"],
    installCommand: "npx skild add pdf-reader",
    createdAt: "2026-04-10T09:15:00Z",
    authorClerkId: "user_ghi789",
    authorEmail: "carol@example.com",
  },
  {
    id: "4",
    title: "Database Query",
    slug: "database-query",
    description: "Provides agents with the ability to run read-only SQL queries against a connected database.",
    category: "Data",
    tags: ["sql", "database", "query"],
    installCommand: "npx skild add database-query",
    createdAt: "2026-04-15T11:45:00Z",
    authorClerkId: "user_jkl012",
    authorEmail: "dave@example.com",
  },
  {
    id: "5",
    title: "Email Sender",
    slug: "email-sender",
    description: "Lets agents compose and send emails via SMTP or a transactional email provider.",
    category: "Communication",
    tags: ["email", "smtp", "notification"],
    installCommand: "npx skild add email-sender",
    createdAt: "2026-04-20T16:00:00Z",
    authorClerkId: "user_mno345",
    authorEmail: "eve@example.com",
  },
];
